### ISSUE TITLE
Bad Gateway 502 with traefik

### ISSUE THREAD

**Issue by YoMamasNerd** [Tkd-Alex/Twitch-Channel-Points-Miner-v2#471]
**Describe the bug**
I'm using traefik to expose the web analytics to the web and it shows a 502 bad gateway.

**To Reproduce**
1. Set up a working Docker setup
2. install a working traefik instance
3. install twitch miner
4. try to expose the analytics

**Expected behavior**
The analytics should show up at the expected URL

**Desktop (please complete the following information):**
 - OS: Ubuntu
 - Docker host
 - newest Docker image

**Additional context**
My docker config: [(Image for better readability)](https://pasteboard.co/OiQPS2sUKGZV.png)
```
  twitch-miner_app:
    image: tkdalex/twitch-channel-points-miner-v2
    container_name: twitch-miner_app
    restart: unless-stopped
    tty: true
    environment:
      - TERM=xterm-256color
    volumes:
      - ./twitch-miner/analytics:/usr/src/app/analytics
      - ./twitch-miner/cookies:/usr/src/app/cookies
      - ./twitch-miner/logs:/usr/src/app/logs
      - ./twitch-miner/run.py:/usr/src/app/run.py:ro
    labels:
      - "traefik.enable=true"
      - "traefik.http.middlewares.twitch-miner-https.redirectscheme.scheme=https"
      - "traefik.http.routers.twitch-miner-http.entrypoints=web"
      - "traefik.http.routers.twitch-miner-http.rule=Host(`twitch.xxx.xxx`)"
      - "traefik.http.routers.twitch-miner-http.middlewares=twitch-miner-https@docker"
      - "traefik.http.routers.twitch-miner.entrypoints=web-secure"
      - "traefik.http.routers.twitch-miner.rule=Host(`twitch.xxx.xxx`)"
      - "traefik.http.routers.twitch-miner.tls=true"
      - "traefik.http.routers.twitch-miner.tls.certresolver=default"
      - "traefik.http.services.twitch-miner.loadbalancer.server.port=8080"
      - "com.centurylinklabs.watchtower.enable=true"
```

My run.py analytics section
```
twitch_miner.analytics(host="127.0.0.1", port=8080, refresh=5)
```
