### ISSUE TITLE
Plesk - Environment variables

### ISSUE THREAD

**Issue by TheRealDK1337** [Tkd-Alex/Twitch-Channel-Points-Miner-v2#555]
I would love to use the Docker version on my Plesk server. Every time i start the container i get the following error:

python: can't open file 'run.py': [Errno 2] No such file or directory

I already tried mounting all required folders and files to the container, but it won´t work.

Could you add some env variables for setting the folder and file paths?
Or give me a hint how i could use the container on plesk?

Thank you for your help.

**Comment by draxxy9** [comment]
If you're using docker-compose, the file structure should appear as below:
```
Twitch-Channel-Points-Miner-v2-master/
├── analytics
├── cookies
├── docker-compose.yml
├── Dockerfile
├── LICENSE
├── logs
├── README.md
├── requirements.txt
├── run.py
├── setup.py
└── TwitchChannelPointsMiner
```
If you've cloned the git repository, most likely you don't have a "run.py", but an "example.py". In that case, please follow the instructions available here: https://github.com/Tkd-Alex/Twitch-Channel-Points-Miner-v2#how-to-use

Alternatively, if you've set it up the way I've described above and it still isn't working, your Plesk configuration (in lieu of the compose file) should be something like this:
```
version: '3.9'
services:
    twitch-miner:
        container_name: twitch-miner
        image: tkdalex/twitch-channel-points-miner-v2
        tty: true
        ports:
            - 5000:5000
        volumes:
            - ./analytics:/usr/src/app/analytics
            - ./cookies:/usr/src/app/cookies
            - ./logs:/usr/src/app/logs
            - ./run.py:/usr/src/app/run.py:ro
        environment:
            - TERM=xterm-256color
        restart: unless-stopped
```
