### ISSUE TITLE
Cant connect to the docker image trough nginx reverse proxy 

### ISSUE THREAD

**Issue by SIGTERM-015** [Tkd-Alex/Twitch-Channel-Points-Miner-v2#583]
**Describe the bug**
I can't connect the miner's container through a nginx reverse proxy, it says 503 bad gateway (when setting the host as localhost) or Not found (when setting the host as 0.0.0.0

**To Reproduce**
1. Have an nginx container in the same network as miners
2. set a location like this 
```
     location /miner/ {
      root /usr/src/app/assets;
      index charts.html;
      proxy_set_header Host localhost;
      proxy_pass http://miner:3040;
    } 
```  
3. go to yourdomain.com/miner

**Expected behavior**
show the analytics page 

**Desktop (please complete the following information):**
 - OS: ubunut 20.04 docker image

**Additional context**
my full ngin.conf
```
worker_processes  1;  ## Default: 1
worker_rlimit_nofile 8192;

events {}
http {
  server {
    listen 80;
    server_name node1.nereacassian.com;
  
    location ~ ^/\.well-known {
      root /var/www/html;
      allow all;
    }
  
    location / {
        return 301 https://$host$request_uri;
    }
  }
  
  server {
    listen 443 ssl;
    
    ssl_certificate     /ssl/nereacassian_com.crt;
    ssl_certificate_key /ssl/nereacassian_com.key;
  
    server_name node1.nereacassian.com;
  
    location / {
      root /var/www/pufferpanel;
      proxy_set_header X-Real-IP $remote_addr;
      proxy_http_version 1.1;
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
      proxy_set_header Host $http_host;
      proxy_set_header Connection "Upgrade";
      proxy_set_header Upgrade $http_upgrade;
      proxy_set_header X-Nginx-Proxy true;
      proxy_set_header X-Forwarded-Proto $scheme;
      proxy_pass http://pufferpanel:8080;
    }

    location /miner/ {
      root /usr/src/app/assets;
      index charts.html;
      proxy_set_header Host localhost;
      proxy_pass http://miner:3040;
    }   
    
  }
}
```
my docker compose 
```
version: "3.9"

services:
  miner:
    image: tkdalex/twitch-channel-points-miner-v2
    container_name: miner
    restart: unless-stopped
    stdin_open: true
    tty: true
    environment:
      - TERM=xterm-256color
    volumes:
      - ./analytics:/usr/src/app/analytics
      - ./cookies:/usr/src/app/cookies
      - ./logs:/usr/src/app/logs
      - ./run.py:/usr/src/app/run.py:ro
    ports:
      - 3040:3040
    networks:
      - agsp
    depends_on:
      - webserver
networks:
  agsp:
    external: true


```
