### ISSUE TITLE
Docker Support

### ISSUE THREAD

**Issue by SethFalco** [Tkd-Alex/Twitch-Channel-Points-Miner-v2#79]
**Is your feature request related to a problem? Please describe.**
It would  be great to be able to run this without having to worry about having the correct version of Python / pip on my environment, and isolated from other system resources.

**Describe the solution you'd like**
To be able to run the script through Docker. I'm willing to contribute towards anything Docker related myself, however before it'd be easier if the script had:
* a way to have to configure the settings via environment variables.
* a way to authenticate to Twitch non-interactively
  * would an authorization token be viable?
  * making password an environment variable and setting would work for non 2FA users
  * to cover 2FA users, either a setting for TOTP which users will just have to then run quickly after configuring the first time, or to generate the cookies externally and mount the `./cookies/` folder as a volume

When or if that's done, a `Dockerfile` and `docker-compose.yml` can be created which can be configured via environment variables.

The following should work for a starting point:

**.dockerignore**
```
.github/
assets/
cookies/
logs/
.dockerignore
.gitignore
Dockerfile
example.py
LICENSE
run.py

*.yml
*.yaml
*.md
```

**docker-compose.yml**
```yml
version: "3.8"
services:
  miner:
    build: ./
    restart: "unless-stopped"
    volumes:
      - ./logs/:/home/logs/
    environment:
      twitch_miner_username: "USERNAME"
      twitch_miner_password: "AUTH"
```

**Dockerfile**
```Dockerfile
FROM python:3.9.1-slim-buster
LABEL maintainer="Tkd-Alex"

WORKDIR /home/
COPY ./ /home/

RUN echo "Adding miner system group and user" && \
    groupadd --system --gid 1000 miner && \
    useradd --system --gid miner --uid 1000 --shell /bin/bash miner && \
    echo "Install pip dependencies" && \
    pip install -r requirements.txt;

USER miner

ENTRYPOINT ["python", "run.py"]
```

**Comment by Tkd-Alex** [comment]
Great idea! Docket It's always a good choice for every project. 

I don't have too much experience, usually the docker-compose It's useful when we have more than one container to merge or not? For this project a simple Docker It's not enough?

Currently, I've very busy with a lot of things and I want just to complete the current work-in-progress feature. I'll start to work on this asap

But If you have free time and experience you can work on it and submit a PR 🥳

**Comment by SethFalco** [comment]
> I don't have too much experience, usually the docker-compose It's useful when we have more than one container to merge or not? For this project a simple Docker It's not enough?

Ahh yeah, you're right. I _personally_ just prefer to make a `docker-compose.yml` if I'm intending to continue to run and configure a container as opposed to only running it as a one-off. If you think it's not suitable, I see no problem with ignoring that one; it can just be left to user discretion. 

It's not unheard of to do this though, for example looking at the docs for two projects I also run via Docker:
* https://github.com/pi-hole/docker-pi-hole/#quick-start
* https://jellyfin.org/docs/general/administration/installing.html#docker

These both include a `docker-compose.yml` despite being a single service.

**Comment by Tkd-Alex** [comment]
I've written this little note about docker-compose only for personal doubt.
For me It's the same use only the Dockerfile or both with docker-compose. Obviously in the future if we need another service we have already the compose file :smiley:

**Comment by Tkd-Alex** [comment]
@SethFalco you think It's wrong link the `run.py` via volumes? So we can easily set up the scripts. 
In fact, I don't understand why `run.py` It's in .dockerignore :thinking:

**Comment by SethFalco** [comment]
> @SethFalco you think It's wrong link the `run.py` via volumes? So we can easily set up the scripts.
> In fact, I don't understand why `run.py` It's in .dockerignore thinking

The `run.py` is in the `.dockerignore` because when the base image is build, a default `run.py` file shouldn't be provided, right? You'd only want to attach that via volumes. (`.dockerignore` is only excluding files for the base image, it will not ignore files for volumes.)

So basically to build the base image without the `run.py`, so the user can add their own `run.py` via a volume.

---

_Ideally_, I think the `run.py` shouldn't be required to run this in a Docker container, though. Or at least the configuration of the script shouldn't be in the `run.py` file. The optimal approach I think would be if as much configuration as possible could be done through environment variables alone, and that a `run.py` could be added as a volume for users that need the flexibility of it, such as per streamer settings.

This is why I thought it might be nice if settings could be done via environment variables first, before making a Dockerfile.

**Example**  
```yml
version: "3.8"
services:
  miner:
    build: ./
    restart: "unless-stopped"
    volumes:
      - ./logs/:/logs/
    environment:
      twitch_miner_username: "USERNAME"
      twitch_miner_password: "PASSWORD"
      twitch_miner_claim_drops_startup: false
      twitch_miner_logger_settings_save: true
      twitch_miner_logger_settings_console_level: "INFO"
      twitch_miner_logger_settings_file_level: "DEBUG"
      twitch_miner_logger_settings_emoji: true
      twitch_miner_logger_settings_less: false
      twitch_miner_streamer_settings_make_predictions: false
      twitch_miner_streamer_settings_follow_raid: true
      twitch_miner_streamer_settings_claim_drops: false
      twitch_miner_streamer_settings_watch_streak: true
      twitch_miner_mine_streamers: "streamer1,streamer2,streamer3,streamer4,streamer5"
      twitch_miner_mine_followers: true
```
> Variable names are just examples based on the object structure, they can be anything though.
